<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.9.7 on win32)" generated="20230620 10:13:28.474" rpa="true" schemaversion="3">
<suite id="s1" name="Tasks" source="C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\tasks.robot">
<test id="s1-t1" name="Get Data from JSON and use that in robot" line="18">
<kw name="Send Report to UI Modeler" library="customFunctions">
<kw name="Set Suite Variable" library="BuiltIn">
<arg>${report}</arg>
<arg>${error_list}</arg>
<doc>Makes a variable available everywhere within the scope of the current suite.</doc>
<msg timestamp="20230620 10:13:28.549" level="INFO">${report} = []</msg>
<status status="PASS" starttime="20230620 10:13:28.549" endtime="20230620 10:13:28.550"/>
</kw>
<kw name="POST">
<var>${resp}</var>
<arg>${HTTP_LOCAL_SERVER}</arg>
<arg>json=${report}</arg>
<msg timestamp="20230620 10:13:28.552" level="FAIL">No keyword with name 'POST' found.</msg>
<status status="FAIL" starttime="20230620 10:13:28.552" endtime="20230620 10:13:28.552"/>
</kw>
<kw name="Status Should Be">
<arg>OK</arg>
<arg>${resp}</arg>
<status status="NOT RUN" starttime="20230620 10:13:28.554" endtime="20230620 10:13:28.554"/>
</kw>
<status status="FAIL" starttime="20230620 10:13:28.549" endtime="20230620 10:13:28.555"/>
</kw>
<status status="FAIL" starttime="20230620 10:13:28.548" endtime="20230620 10:13:28.555">No keyword with name 'POST' found.</status>
</test>
<doc>Get Data from JSON and use that in robot.</doc>
<status status="FAIL" starttime="20230620 10:13:28.475" endtime="20230620 10:13:28.555"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tasks</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Tasks">Tasks</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230620 10:13:28.496" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\tasks.robot' on line 3: Importing library 'RPA.Browser.Selenium' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.499" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\tasks.robot' on line 4: Importing library 'RPA.HTTP' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.508" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\tasks.robot' on line 7: Importing library 'RPA.JSON' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.512" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\tasks.robot' on line 8: Importing library 'RPA.Desktop' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.523" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\customFunctions.robot' on line 3: Importing library 'RPA.Browser.Selenium' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.526" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\customFunctions.robot' on line 4: Importing library 'RPA.HTTP' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.532" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\customFunctions.robot' on line 7: Importing library 'RPA.JSON' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.535" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\customFunctions.robot' on line 8: Importing library 'RPA.Desktop' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230620 10:13:28.546" level="ERROR">Error in file 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\customFunctions.robot' on line 10: Importing library 'C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\OCR.py' failed: ModuleNotFoundError: No module named 'pytesseract'
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions\OCR.py", line 1, in &lt;module&gt;
    import pytesseract
PYTHONPATH:
  C:\Users\Admin\Desktop\model-driven-RPA\Database\Robot\CustomFunctions
  C:\ProgramData\Anaconda3\Scripts\robot.exe
  C:\ProgramData\Anaconda3\python39.zip
  C:\ProgramData\Anaconda3\DLLs
  C:\ProgramData\Anaconda3\lib
  C:\ProgramData\Anaconda3
  C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages
  C:\ProgramData\Anaconda3\lib\site-packages\locket-0.2.1-py3.9.egg
  C:\ProgramData\Anaconda3\lib\site-packages\win32
  C:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  C:\ProgramData\Anaconda3\lib\site-packages\Pythonwin</msg>
</errors>
</robot>
